name: Generate GitHub Stats

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      ### CONTRIBUTION GRAPH 
      
      - name: Contributions Calendar (dark)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filename: assets/contributions-dark.svg
          base: ""
          plugin_isocalendar: yes
          config_timezone: Asia/Kolkata

      - name: Contributions Calendar (light)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filename: assets/contributions-light.svg
          base: ""
          plugin_isocalendar: yes
          config_order: base.header, base.activity, base.repositories
          config_timezone: Asia/Kolkata
      
      ### CODING STREAK 
      
      - name: Fetch Streak Stats (dark)
        run: curl -o assets/streak-dark.svg "https://github-readme-streak-stats.herokuapp.com/?user=koustavcodes&theme=tokyonight&hide_border=true"

      - name: Fetch Streak Stats (light)
        run: curl -o assets/streak-light.svg "https://github-readme-streak-stats.herokuapp.com/?user=koustavcodes&theme=default&hide_border=true"
      
      ### LANGUAGES â€” % of code written
      
      - name: Fetch Languages (dark)
        run: curl -o assets/languages-dark.svg "https://github-readme-stats.vercel.app/api/top-langs/?username=koustavcodes&layout=compact&theme=tokyonight&hide_border=true"

      - name: Fetch Languages (light)
        run: curl -o assets/languages-light.svg "https://github-readme-stats.vercel.app/api/top-langs/?username=koustavcodes&layout=compact&theme=default&hide_border=true"

      ### COMMIT IF UPDATED
      
      - name: Commit if changed
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          if git diff --quiet; then
            echo "No changes."
          else
            git add assets/*.svg
            git commit -m "ðŸ“Š Updated stats $(date)"
            git push
          fi
